# Generated by Django 5.1 on 2024-08-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bybit', '0008_entryprice_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='take_profit_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
